word_first_3 = input()
word_last_2 = input()
middle_word = input()
print("First 3 letters: {}".format(word_first_3))
print("Last 2 letters: {}".format(word_last_2))
print("Middle word: {}".format(middle_word))
